In [ ]:
Base Matrix test

In [2]:
import random
import numpy as np

In [3]:
# lass 4*8 Base Matrix machen
m = 4
A = np.zeros ([m,m], dtype=int)

# Dual Diagonal Teil 
T = np.eye(m, dtype=int) + np.eye(m, k=-1, dtype=int)


base = np.hstack ((A,T))
print(base)

[[0 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 0 0]
 [0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 1 1]]


In [270]:
T = np.eye(4, dtype=int) + np.eye(4, k=-1, dtype=int)
array = np.random.randint (63, size=[4,4])
array = np.hstack((array,T))
#array[array == 0] = -1
print (array)




for c in range (1, array.shape[1], 1):
 #print ("HORIZONTAL BREITE", c)
 for r in range (1, array.shape[0], 1):
  #print ("VERTIKAL BREITE", r)


  for i in range (array.shape[0]-r):
    for j in range (array.shape[1]-c):
        #print (array[i][j], array[i+r][j],array[i+r][j+c],array[i][j+c] )
        # EIGENTLICH STATT 0 PRÜFUNG AUF -1!
        if array[i][j] != 0 and array[i+r][j] != 0 and array[i][j+c] != 0 and array[i+r][j+c] != 0:
          if ((array[i][j] - array[i+r][j]) + (array[i+r][j+c]-array[i][j+c])) % 64 == 0:
           print(" PROBLEM!")
             
    
           print (array[i][j], array[i+r][j],array[i+r][j+c],array[i][j+c] )
          

[[ 3  5  5 39  1  0  0  0]
 [44 23 20 13  1  1  0  0]
 [54 61 21 15  0  1  1  0]
 [31  6 29 44  0  0  1  1]]


In [32]:
# UND WAS WENN SCALING 4 WÄRE
T = np.eye(4, dtype=int) + np.eye(4, k=-1, dtype=int)
array = np.random.randint (4, size=[4,4])
array = np.hstack((array,T))
#array[array == 0] = -1
print (array)




for c in range (1, array.shape[1], 1):
 #print ("HORIZONTAL BREITE", c)
 for r in range (1, array.shape[0], 1):
  #print ("VERTIKAL BREITE", r)


  for i in range (array.shape[0]-r):
    for j in range (array.shape[1]-c):
        #print (array[i][j], array[i+r][j],array[i+r][j+c],array[i][j+c] )
        # EIGENTLICH STATT 0 PRÜFUNG AUF -1!
        if array[i][j] != 0 and array[i+r][j] != 0 and array[i][j+c] != 0 and array[i+r][j+c] != 0:
          if ((array[i][j] - array[i+r][j]) + (array[i+r][j+c]-array[i][j+c])) % 4 == 0:
           print(" PROBLEM!")
             
    
           print (array[i][j], array[i+r][j],array[i+r][j+c],array[i][j+c] )

[[2 2 2 2 1 0 0 0]
 [0 3 0 2 1 1 0 0]
 [3 0 0 2 0 1 1 0]
 [0 3 0 1 0 0 1 1]]
 PROBLEM!
2 2 1 1
 PROBLEM!
2 2 1 1


In [ ]:
'''np.eye(64, k=0, dtype=int)
matrix = np.zeros((64*array.shape[0],64*array.shape[1]))

for i in range (array.shape[0]):
   for j in range (array.shape[1]): 
    print(array[i][j])
    m = np.eye (64, k = array[i][j],dtype=int) # geschifftete 64*64
    print(m)
    
    matrix = np.stack( matrix, m)'''


'np.eye(64, k=0, dtype=int)\nmatrix = np.zeros((64*array.shape[0],64*array.shape[1]))\n\nfor i in range (array.shape[0]):\n   for j in range (array.shape[1]): \n    print(array[i][j])\n    m = np.eye (64, k = array[i][j],dtype=int) # geschifftete 64*64\n    print(m)\n    \n    matrix = np.stack( matrix, m)'

In [ ]:
array = np.array ([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])
print(array.shape)

# FUNK 
for c in range (1, array.shape[1], 1):
 print ("HORIZONTAL BREITE", c)
 for r in range (1, array.shape[0], 1):
  print ("VERTIKAL BREITE", r)


  for i in range (array.shape[0]-r):
    for j in range (array.shape[1]-c):
    
          print (array[i][j], array[i+r][j],array[i+r][j+c],array[i][j+c] )
          

(3, 4)


[[1 2 3]
 [4 5 6]]
